export enum StockMovementType {
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  PURCHASE_COMPLETED = 'PURCHASE_COMPLETED',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT'
}
